# Rakefile

require 'rake'
require 'rspec/core/rake_task'


######################################################################
# Control the number of parallel processes:
#   => rake api_tests_parallel TEST_ENV_NUMBER=4
# Use tags to run specific tests:
#   => rake api_tests_parallel SPEC_OPTS="--tag focus"
# Set API_KEY 
#   => API_KEY=************** rake api_tests_parallel
######################################################################

# DEFAULT_KEY = 'c8c5dddddddddd69d96f06331af9'

desc "Run API tests in parallel"
task :api_tests_parallel do
  # You can pass ENV vars like API_KEY here too
  if ENV['API_KEY'].nil?
    pp "check your profile in iCANDID to get the API_KEY"
    pp "usage: rake api_tests API_KEY=*********" 
    exit
  end
  sh "bundle exec parallel_rspec spec/searchquery_api/"
end

# Define a task to run all API-related specs
desc "Run API integration tests"
RSpec::Core::RakeTask.new(:api_tests) do |t|
  if ENV['API_KEY'].nil?
    pp "check your profile in iCANDID to get the API_KEY"
    pp "usage: rake api_tests API_KEY=*********" 
    exit
  end
  
  #if ENV['INDEX'].nil?
  #  ENV['INDEX'] = "any,title,author,dataset"
  #end
  
  t.pattern = 'spec/searchquery_api/*_spec.rb' 
  t.rspec_opts = "--tag #{ENV['TAG']}" if ENV['TAG']
end

# Optional: define a default task
task default: :api_tests

# Optional: run tests with a specific environment variable
desc "Run API tests with custom API key"
task :api_with_key do
  if ENV['API_KEY'].nil?
    pp "check your profile in iCANDID to get the API_KEY"
    pp "usage: rake api_tests API_KEY=*********" 
    exit
  end
  ENV['API_KEY'] ||= DEFAULT_KEY
  Rake::Task[:api_tests].invoke
end
